:sparkles: add Industry Color Priority When Take Effect
Game-as-a-Service/Machi-Koro-Java pull request #78
Opened 2023-04-30 10:06 UTC by shmily7829

#74

2023-05-02 05:18 UTC, keytsai requested changes

2023-05-02 05:18 UTC, keytsai commented on src/main/java/domain/card/establishment/IndustryColor.java
> +    BLUE(2),
這邊可以照發動效果順序排列:
```java
RED(1),
BLUE(2),
GREEN(3),
PURPLE(4);
```

2023-05-02 05:18 UTC, keytsai commented on src/test/java/usecase/DistributeResourcesTest.java
> +    ///重新依照產業顏色(red->blue->green->purple)排序
再加入一張紫色卡牌，以測試到所有產業顏色順序

2023-05-04 03:18 UTC, shmily7829 commented
@keytsai 
resolved all review, plz check, thx.

2023-05-04 03:24 UTC, keytsai approved these changes

2023-05-04 03:24 UTC, merged